#!/bin/bash
REQUIRED_FILES="lab1.pdf mmul1.c mmul2.c"

# usage
if [ $# -ne 1 ]
then
	echo "Usage: $0 Your_UID" 1>&2
	exit
fi
TMP_DIR=/tmp/${1}_tmp
FOLDER_NAME=$1

ZIP_FILE="lab1-${1}.tar.gz"

# clean any existing files
rm -rf ${TMP_DIR}
mkdir ${TMP_DIR}

if [ ! -f ${ZIP_FILE} ]; then
    echo "ERROR: Cannot find ${ZIP_FILE}, please ensure that this script is put in the same directory as your ${ZIP_FILE} file. Otherwise, check the tar file name" 1>&2
    rm -rf ${TMP_DIR}
    echo "rmd"
    exit 1
fi

# change directory to the grading folder
cp ${ZIP_FILE} ${TMP_DIR}
cd ${TMP_DIR}

# unzip the submission zip file 
tar -xzf ${ZIP_FILE}
if [ "$?" -ne "0" ]; then 
    echo "ERROR: Cannot unzip ${ZIP_FILE} to ${TMP_DIR}"
    rm -rf ${TMP_DIR}
    exit 1
fi

if [ ! -d ${FOLDER_NAME} ];
then
echo "Make sure your folder name is EXACTLY the same as UID you typed"
rm -rf ${TMP_DIR}
exit 1
fi

cd ${FOLDER_NAME}

# check the existence of the required files
for FILE in ${REQUIRED_FILES}
do
    if [ ! -f ${FILE} ]; then
		echo "ERROR: Cannot find ${FILE} in the root folder of your tar file" 1>&2
		rm -rf ${TMP_DIR}
		exit 1
    fi
done

echo "The format check was successful. Please upload your ${ZIP_FILE} file to Gradescope"
rm -rf ${TMP_DIR}
exit 0
